version: '3'
services:
    mysql:
        container_name: demo-mysql
        build: ./mysql
        environment:
            - MYSQL_DATABASE=demo
            - MYSQL_USER=demo
            - MYSQL_PASSWORD=demodemo
            - MYSQL_ROOT_PASSWORD=demodemo
            - TZ=Japan
        volumes:
            - "demo-volume:/var/lib/mysql"
        ports:
            - "3306:3306"
        restart: always
    
    # java:
    #     container_name: demo-java
    #     build: ../
    #     ports:
    #         - "8080:8080"
    #     environment:
    #         spring.datasource.url: jdbc:mysql://demo-mysql:3306/demo
    #     working_dir: /app
    #     depends_on:
    #         - mysql
    #     restart: always
    #     tty: true

volumes:
    demo-volume:
        name: demo-volume
        external: true